/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.senai.view;

import br.com.senai.util.Config;
import br.com.senai.dao.EscolaDAO;
import br.com.senai.dao.FichaDAO;
import br.com.senai.entities.Escola;
import br.com.senai.entities.Ficha;
import java.awt.Image;
import java.awt.event.ItemEvent;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author alunoo
 */
public class AlterarFicha extends javax.swing.JFrame {

    /**
     * Creates new form OpcoesAdministrativas
     */
    public AlterarFicha() {
        initComponents();
        Config.configurarJanela(this);

        Config.fillComboBox(cbEscolas, new EscolaDAO().escolasPermitidas(Config.usuario));
        atualizarValores();
        icon.setIcon(new ImageIcon(new ImageIcon("imagens/icones/13.png").getImage().getScaledInstance(37, 37, Image.SCALE_SMOOTH)));

    }

    private void atualizarValores() {

        DefaultTableModel tableModel = (DefaultTableModel) tValores.getModel();
        tableModel.setNumRows(0);

        if (!cbEscolas.getSelectedItem().toString().equalsIgnoreCase("Selecione...")) {

            try {

                for (Ficha ficha : new FichaDAO().pegarFichaEscola((Escola) cbEscolas.getSelectedItem())) {
                    tableModel.addRow(new Object[]{ficha, ficha.getValor(), new SimpleDateFormat("dd-MM-yyyy").format(ficha.getDataAlteracao()), ficha.getEscola().getNome()});
                }

            } catch (IllegalArgumentException ex) {

            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tValores = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        tfValorFicha = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        cbEscolas = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        icon = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Valor lanche -");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("Valor do lanche");
        jLabel4.setToolTipText("Alterar senha do usuário");

        jLabel1.setText("Valor do lanche:");

        tValores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Valor", "Data alteração"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tValores);
        if (tValores.getColumnModel().getColumnCount() > 0) {
            tValores.getColumnModel().getColumn(0).setMinWidth(0);
            tValores.getColumnModel().getColumn(0).setPreferredWidth(0);
            tValores.getColumnModel().getColumn(0).setMaxWidth(0);
            tValores.getColumnModel().getColumn(2).setResizable(false);
        }

        jButton1.setText("Cadastrar");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton4.setText("Alterar");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        cbEscolas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbEscolasItemStateChanged(evt);
            }
        });

        jLabel3.setText("Selecione a  escola:");

        jButton5.setText("Cancelar");
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbEscolas, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(icon, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tfValorFicha, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(20, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(141, 141, 141)
                                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton1, jButton4});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(icon, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbEscolas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfValorFicha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addGap(20, 20, 20))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton1, jButton4});

        setSize(new java.awt.Dimension(383, 404));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
 Ficha f = new Ficha();
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (!cbEscolas.getSelectedItem().toString().equalsIgnoreCase("Selecione...")) {

            if (!tfValorFicha.getText().isEmpty()) {
                double valor = 0;

                if (new FichaDAO().pegarFichaNaDataEEscola(new Date(), (Escola) cbEscolas.getSelectedItem()).isEmpty()) {

                    try {
                        valor = Double.parseDouble(tfValorFicha.getText());

                        f.setDataAlteracao(new Date());
                        f.setValor(valor);
                        f.setEscola((Escola) cbEscolas.getSelectedItem());

                        new FichaDAO().salvar(f);

                        atualizarValores();

                        new Config().mensagemSalvo();

                        tfValorFicha.setText(null);
                        tfValorFicha.requestFocus();
                        Config.fillComboBox(cbEscolas, new EscolaDAO().escolasPermitidas(Config.usuario));

                    } catch (NumberFormatException ex) {
                        try {
                            valor = Double.parseDouble(tfValorFicha.getText().replace(",", "."));

                            f.setDataAlteracao(new Date());
                            f.setValor(valor);
                            f.setEscola((Escola) cbEscolas.getSelectedItem());

                            new FichaDAO().salvar(f);

                            atualizarValores();

                            new Config().mensagemSalvo();

                            tfValorFicha.setText(null);
                            tfValorFicha.requestFocus();
                            Config.fillComboBox(cbEscolas, new EscolaDAO().escolasPermitidas(Config.usuario));
                        } catch (NumberFormatException ex1) {
                            JOptionPane.showMessageDialog(null, "Insira os valores corretamente.");
                            tfValorFicha.setText(null);
                        }

                    }

                } else {
                    JOptionPane.showMessageDialog(null, "Valor já inserido nessa data!");
                    tfValorFicha.setText(null);
                }
            }

        } else {
            JOptionPane.showMessageDialog(null, "Selecione uma escola.");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        if (tValores.getSelectedRowCount() > 0) {

            Ficha f = (Ficha) tValores.getValueAt(tValores.getSelectedRow(), 0);

            String valor = (String) JOptionPane.showInputDialog(null, "Valor na data: " + new SimpleDateFormat("dd-MM-yyyy").format(f.getDataAlteracao()), "Alterar dados ", JOptionPane.QUESTION_MESSAGE, null, null, f.getValor());
            double valorFicha = 0.0;
            try {
                if (valor != null) {

                    valorFicha = Double.parseDouble(valor);

                    f.setValor(valorFicha);

                    new FichaDAO().atualizar(f);

                    atualizarValores();

                    JOptionPane.showMessageDialog(null, "Salvo");

                }
            } catch (NumberFormatException ex) {

                try {
                    valorFicha = Double.parseDouble(valor.replace(",", "."));

                    f.setValor(valorFicha);

                    new FichaDAO().atualizar(f);

                    atualizarValores();

                    JOptionPane.showMessageDialog(null, "Salvo");

                } catch (NumberFormatException ex1) {
                    JOptionPane.showMessageDialog(null, "ERRO");
                }

            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void cbEscolasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbEscolasItemStateChanged

        if (evt.getStateChange() == ItemEvent.SELECTED) {
            if (!cbEscolas.getSelectedItem().toString().equalsIgnoreCase("Selecione...")) {

                try {
                    DefaultTableModel tableModel = (DefaultTableModel) tValores.getModel();

                    tableModel.setNumRows(0);

                    for (Ficha ficha : new FichaDAO().pegarFichaEscola((Escola) cbEscolas.getSelectedItem())) {

                        tableModel.addRow(new Object[]{ficha, ficha.getValor(), new SimpleDateFormat("dd-MM-yyyy").format(ficha.getDataAlteracao())});

                    }

                } catch (ClassCastException ex) {

                }
            }
        }

    }//GEN-LAST:event_cbEscolasItemStateChanged

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbEscolas;
    private javax.swing.JLabel icon;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tValores;
    private javax.swing.JTextField tfValorFicha;
    // End of variables declaration//GEN-END:variables
}
