/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.senai.view;

import br.com.senai.util.Config;
import br.com.senai.dao.AlunoDAO;
import br.com.senai.dao.Curso_e_EscolaDAO;
import br.com.senai.dao.EscolaDAO;
import br.com.senai.dao.TurmaDAO;
import br.com.senai.dao.TurnoDAO;
import br.com.senai.entities.Aluno;
import br.com.senai.entities.Curso;
import br.com.senai.entities.Curso_e_Escola;
import br.com.senai.entities.Escola;
import br.com.senai.entities.Turma;
import br.com.senai.entities.Turno;
import java.awt.event.ActionEvent;
import java.awt.event.ItemEvent;
import java.awt.event.KeyEvent;
import javax.swing.AbstractAction;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;
import org.hibernate.HibernateException;

/**
 *
 * @author Hugo
 */
public class CadastroAluno extends javax.swing.JFrame {

    /**
     * Creates new form CadastroAluno
     */
    public CadastroAluno() {
        initComponents();
        Config.configurarJanela(this);
        campoRa.setText(Menu.raAluno);
        Config.fillComboBox(cbEscola, new EscolaDAO().escolasPermitidas(Config.usuario));
        Config.fillComboBox(cbTurno, new TurnoDAO().listar());
        cbCurso.setEnabled(false);

        final AbstractAction escapeAction = new AbstractAction() {
            private static final long serialVersionUID = 1L;

            @Override
            public void actionPerformed(ActionEvent ae) {
                dispose();
            }
        };

        getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW)
                .put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), "ESCAPE_KEY");

        getRootPane().getActionMap().put("ESCAPE_KEY", escapeAction);

    }

    public void cadastrar() {

        if (!cbTurma.getSelectedItem().toString().equalsIgnoreCase("Selecione...")) {

            Turma t = (Turma) cbTurma.getSelectedItem();
            Long id = Long.parseLong(campoRa.getText());

            Aluno a = new Aluno();
            a.setAluno(id);
            a.setTurma(t);
            a.setAtivo(true);

            if (new AlunoDAO().validarTurma(id, t.getTurno()) == null) {

                try {
                    new AlunoDAO().salvar(a);

                    new MensagemSalvo().setVisible(true);
                    dispose();

                } catch (HibernateException e) {

                    new MensagemNaoSalvo().setVisible(true);

                }

            } else {
                JOptionPane.showMessageDialog(null, "O aluno já está realizando um curso nesse turno.");
            }

        } else {

            Config.mensagemInformativa("Selecione uma escola.");
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        campoRa = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cbTurma = new javax.swing.JComboBox();
        tAlunos = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cbEscola = new javax.swing.JComboBox();
        cbCurso = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        cbTurno = new javax.swing.JComboBox();
        tAlunos1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de aluno -");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("R.A. (Registro Acadêmico):");

        campoRa.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        campoRa.setText("[CODIGORA]");

        jLabel6.setText("Turma:");

        cbTurma.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        tAlunos.setMnemonic('s');
        tAlunos.setText("Salvar");
        tAlunos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tAlunos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tAlunosActionPerformed(evt);
            }
        });

        jLabel4.setText("Escola:");

        jLabel5.setText("Curso:");

        cbEscola.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbEscola.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbEscolaItemStateChanged(evt);
            }
        });

        cbCurso.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbCurso.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbCursoItemStateChanged(evt);
            }
        });

        jLabel7.setText("Turno:");

        cbTurno.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbTurnoItemStateChanged(evt);
            }
        });

        tAlunos1.setMnemonic('c');
        tAlunos1.setText("Cancelar");
        tAlunos1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tAlunos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tAlunos1ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setText("Cadastro rápido de aluno");
        jLabel8.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(259, 259, 259))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(cbCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbTurno, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(campoRa))
                                .addComponent(jLabel4)
                                .addComponent(cbTurma, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6)
                                .addComponent(cbEscola, 0, 537, Short.MAX_VALUE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(tAlunos, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tAlunos1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(campoRa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addGap(9, 9, 9)
                .addComponent(cbEscola, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbTurno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(jLabel7)))
                .addGap(30, 30, 30)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbTurma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tAlunos)
                    .addComponent(tAlunos1))
                .addGap(20, 20, 20))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tAlunosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tAlunosActionPerformed
        cadastrar();
    }//GEN-LAST:event_tAlunosActionPerformed

    private void cbEscolaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbEscolaItemStateChanged

        if (cbEscola.getSelectedItem() instanceof Escola) {
            Config.fillComboBox(cbCurso, new Curso_e_EscolaDAO().cursosDaEscola((Escola) cbEscola.getSelectedItem()));
            cbCurso.setEnabled(true);
        } else {
            Config.limparComboBox(cbCurso);
            cbCurso.setEnabled(false);
        }

    }//GEN-LAST:event_cbEscolaItemStateChanged
    public boolean turnoAtivado = false;
    Curso_e_Escola curso_e_Escola = null;
    private void cbCursoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbCursoItemStateChanged
        if (cbCurso.getSelectedItem() instanceof Curso) {
            Config.fillComboBox(cbTurno, new TurnoDAO().listar());
            curso_e_Escola = new Curso_e_EscolaDAO().getCurso_e_Escola((Curso) cbCurso.getSelectedItem(), (Escola) cbEscola.getSelectedItem());
            Config.fillComboBox(cbTurma, new TurmaDAO().pesquisarPorCurso(curso_e_Escola));
        } else {
            Config.limparComboBox(cbTurma);
        }

    }//GEN-LAST:event_cbCursoItemStateChanged

    private void cbTurnoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbTurnoItemStateChanged

        if (evt.getStateChange() == ItemEvent.SELECTED) {

            if (cbTurno.getSelectedItem().toString().equalsIgnoreCase("Selecione...")) {

                turnoAtivado = false;
                Config.limparComboBox(cbTurma);

            } else {
                turnoAtivado = true;

                if (!cbCurso.getSelectedItem().toString().equalsIgnoreCase("Selecione...")) {

                    Config.fillComboBox(cbTurma, new TurmaDAO().pesquisarPorCursoETurno(curso_e_Escola, (Turno) cbTurno.getSelectedItem()));

                }

            }
        }


    }//GEN-LAST:event_cbTurnoItemStateChanged

    private void tAlunos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tAlunos1ActionPerformed
        dispose();
    }//GEN-LAST:event_tAlunos1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel campoRa;
    private javax.swing.JComboBox cbCurso;
    private javax.swing.JComboBox cbEscola;
    private static javax.swing.JComboBox cbTurma;
    private javax.swing.JComboBox cbTurno;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton tAlunos;
    private javax.swing.JButton tAlunos1;
    // End of variables declaration//GEN-END:variables
}
