/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.senai.view;

import br.com.senai.dao.CidadeDAO;
import br.com.senai.dao.EscolaDAO;
import br.com.senai.dao.PermissaoDAO;
import br.com.senai.dao.TipoUsuarioDAO;
import br.com.senai.dao.UsuarioDAO;
import br.com.senai.entities.Cidade;
import br.com.senai.entities.Escola;
import br.com.senai.entities.Permissao;
import br.com.senai.entities.TipoUsuario;
import br.com.senai.entities.Usuario;
import br.com.senai.util.Config;
import java.awt.Image;
import java.awt.event.ItemEvent;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Iterator;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author Hugo
 */
public class EditarUsuarios extends javax.swing.JDialog {

    /**
     * Creates new form EditarUsuarios
     */
    Usuario u = UsuariosCadastrados.editUsuario;
    String tipo;

    public EditarUsuarios() {
        initComponents();

        Config.configurarJanela(this);

        if (Config.usuario.getTipoUsuario().getDescricao().equalsIgnoreCase("Administrador")) {
            Config.fillComboBox(cbCidadeUsuario, new CidadeDAO().cidadesQuePossuemEscola());
        } else {
            Config.fillComboBox(cbCidadeUsuario, new CidadeDAO().cidadesPermitidas(Config.usuario));
        }

        jLabel3.setText(u.getNome());
        jLabel5.setText(u.getEmail());
        jLabel7.setText(u.getLogin());

        jCheckBox1.setSelected(u.getTipoUsuario().getDescricao().equalsIgnoreCase("Gerente"));

        AutoCompleteDecorator.decorate(cbCidadeUsuario);

        fillAdicionadas();

        iconRelatorio.setIcon(new ImageIcon(new ImageIcon("imagens/icones/15.png").getImage().getScaledInstance(43, 43, Image.SCALE_SMOOTH)));

        jButton3.setEnabled(false);
    }

    HashMap<Integer, Permissao> listaPermissao = new HashMap<>();

    public void addEscola(Escola e) {

        Permissao p = (Permissao) listaPermissao.get(e.getId());

        if (p == null) {
            p = new Permissao();
            p.setEscola(e);
            p.setPermissao(true);
            listaPermissao.put(e.getId(), p);

            fillAdicionadas();

        }
    }

    public void fillAdicionadas() {

        for (Permissao p : new PermissaoDAO().doUsuario(u)) {
            listaPermissao.put(p.getEscola().getId(), p);
        }

        DefaultTableModel tableModel = (DefaultTableModel) tPermissoes.getModel();

        tableModel.setNumRows(0);

        Iterator<?> escolas = new ArrayList(listaPermissao.values()).iterator();

        while (escolas.hasNext()) {
            Permissao p = (Permissao) escolas.next();
            tableModel.addRow(new Object[]{p.getEscola(), p.getEscola().getNome()});
        }

    }

    public void apagarEscola(Escola e) {
        listaPermissao.remove(e.getId());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        cbCidadeUsuario = new javax.swing.JComboBox();
        jLabel34 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tPermissoes = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        iconRelatorio = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        cbEscolaCidade = new javax.swing.JComboBox();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);

        jScrollPane1.setBorder(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Nome:");

        jLabel3.setText("jLabel3");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Email:");

        jLabel5.setText("jLabel3");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Login:");

        jLabel7.setText("jLabel3");

        jCheckBox1.setText("Gerente");

        jButton1.setText("Salvar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        cbCidadeUsuario.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbCidadeUsuarioItemStateChanged(evt);
            }
        });

        jLabel34.setText("Cidade:");

        tPermissoes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "escola", "Escola permitidas"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tPermissoes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tPermissoesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tPermissoes);
        if (tPermissoes.getColumnModel().getColumnCount() > 0) {
            tPermissoes.getColumnModel().getColumn(0).setMinWidth(0);
            tPermissoes.getColumnModel().getColumn(0).setPreferredWidth(0);
            tPermissoes.getColumnModel().getColumn(0).setMaxWidth(0);
        }

        jButton3.setText("Remover escola");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setText("Editar usuário");
        jLabel9.setToolTipText("");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Dados gerais do usuário:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Alterar permissões:");

        cbEscolaCidade.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbEscolaCidadeItemStateChanged(evt);
            }
        });

        jLabel16.setText("Escolas da cidade:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(cbEscolaCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel6)
                                .addComponent(jLabel4)
                                .addComponent(jLabel7)
                                .addComponent(jLabel11)
                                .addComponent(jLabel10)
                                .addComponent(jLabel5)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(iconRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel9))
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jSeparator2)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 539, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jButton1)
                                        .addComponent(jCheckBox1))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton2)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel34)
                            .addComponent(cbCidadeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addComponent(jLabel16)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(iconRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel34)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbCidadeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbEscolaCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addGap(9, 9, 9)
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if (jCheckBox1.isSelected()) {
            tipo = "Gerente";
        } else {
            tipo = "Funcionário";
        }

        TipoUsuario tu = new TipoUsuarioDAO().getByName(tipo);

        u.setTipoUsuario(tu);

        new UsuarioDAO().atualizar(u);
        Iterator<?> permissoes = new ArrayList(listaPermissao.values()).iterator();

        while (permissoes.hasNext()) {
            Permissao p = (Permissao) permissoes.next();

            if (new PermissaoDAO().doUsuarioEEscola(u, p.getEscola()) == null) {
                p.setUsuario(u);
                new PermissaoDAO().salvar(p);
            }
        }
        JOptionPane.showMessageDialog(null, "Alterações salvas com sucesso!!");
        dispose();
        UsuariosCadastrados.fillTable();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cbCidadeUsuarioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbCidadeUsuarioItemStateChanged

        if (cbCidadeUsuario.getSelectedItem() instanceof Cidade) {

            if (Config.usuario.getTipoUsuario().getDescricao().equalsIgnoreCase("Administrador")) {
                Config.fillComboBox(cbEscolaCidade, new EscolaDAO().escolaDaCidade((Cidade) cbCidadeUsuario.getSelectedItem()));
            } else {
                Config.fillComboBox(cbEscolaCidade, new EscolaDAO().escolasPermitidasDaCidade(Config.usuario, (Cidade) cbCidadeUsuario.getSelectedItem()));
            }
            cbEscolaCidade.setEnabled(true);
        } else {
            cbEscolaCidade.setEnabled(false);
        }


    }//GEN-LAST:event_cbCidadeUsuarioItemStateChanged

    private void tPermissoesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tPermissoesMouseClicked
        if (tPermissoes.getSelectedRowCount() > 0) {
            jButton3.setEnabled(true);
        } else {
            jButton3.setEnabled(false);
        }
    }//GEN-LAST:event_tPermissoesMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        if (tPermissoes.getSelectedRowCount() > 0) {
            
            Escola escola = (Escola) tPermissoes.getValueAt(tPermissoes.getSelectedRow(), 0);
            Permissao p = new PermissaoDAO().doUsuarioEEscola(u, escola);
            if (p != null) {
                new PermissaoDAO().deletar(p);
            }
            listaPermissao.remove(escola.getId());
            fillAdicionadas();
            jButton3.setEnabled(false);

        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void cbEscolaCidadeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbEscolaCidadeItemStateChanged
        try {
            if (evt.getStateChange() == ItemEvent.SELECTED) {
                if (!cbCidadeUsuario.getSelectedItem().toString().equalsIgnoreCase("Selecione...")) {

                    addEscola((Escola) cbEscolaCidade.getSelectedItem());
                }
            }
        } catch (ClassCastException ex) {

        }
    }//GEN-LAST:event_cbEscolaCidadeItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbCidadeUsuario;
    private javax.swing.JComboBox cbEscolaCidade;
    private javax.swing.JLabel iconRelatorio;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable tPermissoes;
    // End of variables declaration//GEN-END:variables
}
