/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.senai.view;

import br.com.senai.dao.CursoDAO;
import br.com.senai.dao.EscolaDAO;
import br.com.senai.dao.MovimentacaoDAO;
import br.com.senai.entities.Aluno;
import br.com.senai.entities.Curso;
import br.com.senai.entities.Escola;
import br.com.senai.entities.Movimentacao;
import br.com.senai.util.Config;
import br.com.senai.estatistica.GerarRelatorio;
import java.awt.Color;
import java.awt.Image;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JRViewer;
import org.joda.time.DateTime;
import org.joda.time.Days;

/**
 *
 * @author alunoo
 */
public class GerarRelatorios extends javax.swing.JFrame {

    /**
     * Creates new form GerarRelatorios
     */
    public GerarRelatorios() {
        initComponents();
        Config.configurarJanela(this);
        jButton1.setEnabled(false);
        jButton2.setEnabled(false);
        jButton3.setEnabled(false);
        iconRelatorio.setIcon(new ImageIcon(new ImageIcon("imagens/icones/relatorio.png").getImage().getScaledInstance(29, 29, Image.SCALE_DEFAULT)));
        Config.fillComboBox(jComboBox1, new EscolaDAO().escolasPermitidas(Config.usuario));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        dcDataInicio = new com.toedter.calendar.JDateChooser();
        dcDataTermino = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        fundoRelatorio = new javax.swing.JPanel();
        iconRelatorio = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Relatórios -");

        jScrollPane1.setBorder(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Início:");

        dcDataInicio.setToolTipText("Selecione a data de início");
        dcDataInicio.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dcDataInicioPropertyChange(evt);
            }
        });

        dcDataTermino.setToolTipText("Selecione o término do período");
        dcDataTermino.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dcDataTerminoPropertyChange(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Término:");

        jButton1.setText("Relatório por escolas");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("Relatórios");
        jLabel4.setToolTipText("");

        jButton2.setText("Relatório para emissão de notas fiscais");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Escolha o período:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Gerar:");

        fundoRelatorio.setBackground(new java.awt.Color(255, 255, 255));
        fundoRelatorio.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 153), java.awt.Color.white, new java.awt.Color(153, 153, 153), null));

        javax.swing.GroupLayout fundoRelatorioLayout = new javax.swing.GroupLayout(fundoRelatorio);
        fundoRelatorio.setLayout(fundoRelatorioLayout);
        fundoRelatorioLayout.setHorizontalGroup(
            fundoRelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 506, Short.MAX_VALUE)
        );
        fundoRelatorioLayout.setVerticalGroup(
            fundoRelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 574, Short.MAX_VALUE)
        );

        jButton3.setText("Relatório para funcionários");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Escola:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(iconRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(dcDataInicio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dcDataTermino, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel6)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addComponent(fundoRelatorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(27, 27, 27))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(iconRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dcDataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(dcDataTermino, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(fundoRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 666, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        setSize(new java.awt.Dimension(879, 697));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        fundoRelatorio.removeAll();

        JPanel painel = new GerarRelatorio().gerarRelatorioPorEscolas(dcDataInicio.getDate(), dcDataTermino.getDate());

        painel.setSize(fundoRelatorio.getSize());
        painel.setVisible(true);
        painel.setBackground(Color.WHITE);

        fundoRelatorio.add(painel);

        fundoRelatorio.revalidate();
        fundoRelatorio.repaint();


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        fundoRelatorio.removeAll();
        JPanel painel = new GerarRelatorio().gerarRelatorioGeral(dcDataInicio.getDate(), dcDataTermino.getDate());

        painel.setSize(fundoRelatorio.getSize());
        painel.setVisible(true);
        painel.setBackground(Color.WHITE);

        fundoRelatorio.add(painel);

        fundoRelatorio.revalidate();
        fundoRelatorio.repaint();


    }//GEN-LAST:event_jButton2ActionPerformed

    private void dcDataInicioPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dcDataInicioPropertyChange

        if (dcDataInicio.getDate() != null && dcDataTermino.getDate() != null) {

            jButton1.setEnabled(true);
            jButton2.setEnabled(true);

        }


    }//GEN-LAST:event_dcDataInicioPropertyChange

    private void dcDataTerminoPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dcDataTerminoPropertyChange
        if (dcDataInicio.getDate() != null && dcDataTermino.getDate() != null) {
            jButton1.setEnabled(true);
            jButton2.setEnabled(true);
        } else {
            jButton1.setEnabled(false);
            jButton2.setEnabled(false);
        }
    }//GEN-LAST:event_dcDataTerminoPropertyChange

    List<Aluno> alunosManha = new ArrayList<>();
    List<Aluno> alunosTarde = new ArrayList<>();
    List<Aluno> alunosNoite = new ArrayList<>();
    int quantidadeManha;
    int quantidadeTarde;
    int quantidadeNoite;
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        quantidadeManha=0;
        quantidadeTarde=0;
        quantidadeNoite=0;
        Curso curso = new CursoDAO().getCurso("Funcionários");

        Days d = Days.daysBetween(new DateTime(dcDataInicio.getDate()), new DateTime(dcDataTermino.getDate()));

        int days = d.getDays();

        fundoRelatorio.removeAll();
        String corpo = "";

        HashMap mapa = new HashMap();

        mapa.put("DATAEMISSAO", Config.formatarDataResumo(new Date()));
        mapa.put("PERIODO", Config.formatarDataResumo(dcDataInicio.getDate()) + " a " + Config.formatarDataResumo(dcDataTermino.getDate()));
        mapa.put("ESCOLA", ((Escola) jComboBox1.getSelectedItem()).getNome());

        for (int i = 0; i <= days; i++) {
            alunosManha.clear();
            alunosTarde.clear();
            alunosNoite.clear();
            corpo += "<br>__" + Config.formatarDataResumo(new DateTime(dcDataInicio.getDate()).plusDays(i).toDate()) + "________________________________________<br><br>";

            List<Movimentacao> resultados = new MovimentacaoDAO().funcionarios((Escola) jComboBox1.getSelectedItem(), curso, new DateTime(dcDataInicio.getDate()).plusDays(i).toDate());

            for (Movimentacao movimentacao : resultados) {
                switch (new Config().turnoAtual(movimentacao.getHorarioMovimentacao())) {
                    case "Manhã":
                        alunosManha.add((movimentacao.getAluno()));
                        break;
                    case "Tarde":
                        alunosTarde.add((movimentacao.getAluno()));
                        break;
                    case "Noite":
                        alunosNoite.add((movimentacao.getAluno()));
                        break;
                }
            }

            quantidadeManha += alunosManha.size();
            quantidadeTarde += alunosTarde.size();
            quantidadeNoite += alunosNoite.size();

            if (!alunosManha.isEmpty()) {
                corpo += "<font size= \"4\">Turno: <b>Manhã</b> | Quantidade: <b>" + alunosManha.size() + "</b> retirada (s)</font><br><br><i>Funcionários:</i> <br><br>";
                for (Aluno aluno : alunosManha) {
                    corpo += aluno.getNome() + "<br>";
                }
                corpo += "............................................................<br><br>";
            }

            if (!alunosTarde.isEmpty()) {
                corpo += "<font size= \"4\">Turno: <b>Tarde</b> | Quantidade: <b>" + alunosTarde.size() + "</b> retirada (s)</font><br><br><i>Funcionários:</i> <br><br>";
                for (Aluno aluno : alunosTarde) {
                    corpo += aluno.getNome() + "<br>";
                }

                corpo += "_________________________________________________________________________________________________________________________________<br><br>";

            }
            if (!alunosNoite.isEmpty()) {
                corpo += "<font size= \"4\">Turno: <b>Noite</b> | Quantidade: <b>" + alunosNoite.size() + "</b> retirada (s)</font><br><br><i>Funcionários:</i> <br><br>";
                for (Aluno aluno : alunosNoite) {
                    corpo += aluno.getNome() + "<br>";
                }
                corpo += "_________________________________________________________________________________________________________________________________<br><br>";
            }
            corpo += "<i>RESUMO DIÁRIO</i> (" + Config.formatarDataResumo(new DateTime(dcDataInicio.getDate()).plusDays(i).toDate()) + ")<br><br>";
            corpo += "MANHÃ: " + alunosManha.size() + " retirada (s)<br>";
            corpo += "TARDE: " + alunosTarde.size() + " retirada (s)<br>";
            corpo += "NOITE: " + alunosNoite.size() + " retirada (s)<br><br>";
            corpo += "<b>TOTAL: " + (alunosManha.size() + alunosTarde.size() + alunosNoite.size()) + " retirada (s)</b><br>";
        }

        corpo+="-----------------------------------------------------------------------";
        corpo += "<br><br><i>RESUMO GERAL</i><br><br>";
        corpo += "MANHÃ: " + quantidadeManha + " retirada (s)<br>";
        corpo += "TARDE: " + quantidadeTarde + " retirada (s)<br>";
        corpo += "NOITE: " + quantidadeNoite + " retirada (s)<br><br>";
        corpo += "<b>TOTAL: " + (quantidadeManha + quantidadeTarde + quantidadeNoite) + " retirada (s)</b><br>";

        mapa.put("CORPO", corpo);

        String arquivo = "RelatorioFuncionarios.jasper";

        JRViewer relatorio = null;

        try {

            JasperPrint jp = JasperFillManager.fillReport(arquivo, mapa);

            relatorio = new JRViewer(jp);
            relatorio.setZoomRatio(0.5f);
            relatorio.setBackground(Color.WHITE);

            relatorio.setSize(fundoRelatorio.getSize());
            relatorio.setVisible(true);
            relatorio.setBackground(Color.WHITE);

            fundoRelatorio.add(relatorio);

            fundoRelatorio.revalidate();
            fundoRelatorio.repaint();

        } catch (JRException ex) {
            Logger.getLogger(GerarRelatorio.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_jButton3ActionPerformed

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        if (jComboBox1.getSelectedItem() instanceof Escola) {
            jButton3.setEnabled(true);
        } else {
            jButton3.setEnabled(false);
        }
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser dcDataInicio;
    private com.toedter.calendar.JDateChooser dcDataTermino;
    private javax.swing.JPanel fundoRelatorio;
    private javax.swing.JLabel iconRelatorio;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
