/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.senai.view;

import java.awt.Color;
import java.awt.Window;
import javax.swing.Timer;

/**
 *
 * @author Simulado
 */
public class MensagemAguarde2 extends javax.swing.JDialog {

  
//    Window window = new Window(null);
//    JDialog jDialog = new JDialog();
//    String tituloOriginal;
//    private Timer timerDaJanelaQueChamouErro;

//    Timer timer = new Timer(10000, new AbstractAction("banco") {
//        Socket socket = null;
//
//        @Override
//        public void actionPerformed(ActionEvent e) {
//
//            try {
//                socket = new Socket("127.0.0.1", 3306);
//
//                if (socket != null) {
//
//                    ((JFrame) window).setTitle(tituloOriginal);
//
//                    timer.stop();
//                    dispose();
//                    timerDaJanelaQueChamouErro.start();
//                    socket.close();
//                }
//
//            } catch (java.net.NoRouteToHostException ex) {
//            } catch (IOException ex) {
//                Config.mensagemDeErro(ex.getMessage());
//            }
//
//        }
//    });

    public MensagemAguarde2(Window frame, boolean b, Timer time) {

        super(frame);
        initComponents();
        setSize(frame.getSize());
        this.getContentPane().setBackground(Color.WHITE);
        setLocationRelativeTo(frame);

//        setOpacity(0.5f);
//        this.window = frame;
//        if (frame instanceof JFrame) {
//            tituloOriginal = ((JFrame) frame).getTitle();
//            ((JFrame) frame).setTitle(((JFrame) frame).getTitle() + "(Não está respondendo)");
//
//        } else if (frame instanceof JDialog) {
//            tituloOriginal = ((JDialog) frame).getTitle();
//            ((JDialog) frame).setTitle(((JDialog) frame).getTitle() + "(Não está respondendo)");
//
//        }
//
//        timer.start();
//        timerDaJanelaQueChamouErro = time;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jLabel1.setText("Aguarde...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
