/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.senai.view;

import br.com.senai.dao.CidadeDAO;
import br.com.senai.util.Config;
import br.com.senai.dao.EscolaDAO;
import br.com.senai.dao.PermissaoDAO;
import br.com.senai.dao.TipoUsuarioDAO;
import br.com.senai.dao.UsuarioDAO;
import br.com.senai.entities.Cidade;
import br.com.senai.entities.Escola;
import br.com.senai.entities.Permissao;
import br.com.senai.entities.Usuario;
import br.com.senai.util.ProgressoEnviaEmailUsuario;
import java.awt.Font;
import java.awt.Image;
import java.awt.event.ItemEvent;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Iterator;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.apache.commons.lang.RandomStringUtils;
import org.hibernate.exception.ConstraintViolationException;
import org.jdesktop.swingx.prompt.PromptSupport;

/**
 *
 * @author Hugo
 */
public class PainelUsuario extends javax.swing.JPanel {

    /**
     * Creates new form PainelUsuario
     */
    public PainelUsuario() {
        initComponents();
Config.configurarPainel(this);
        init();
    }

    public void init() {

        jButton21.setIcon(new ImageIcon(new ImageIcon("imagens/search.png").getImage().getScaledInstance(50, 50, Image.SCALE_SMOOTH)));

        PromptSupport.setPrompt("usuário@provedor.com / com.br", tfEmail);
        PromptSupport.setFontStyle(Font.BOLD, tfEmail);
        PromptSupport.setFocusBehavior(PromptSupport.FocusBehavior.SHOW_PROMPT, tfEmail);

        if (Config.usuario.getTipoUsuario().getDescricao().equalsIgnoreCase("Administrador")) {
            Config.fillComboBox(cbCidadeUsuario, new CidadeDAO().cidadesQuePossuemEscola());
        } else {
            Config.fillComboBox(cbCidadeUsuario, new CidadeDAO().cidadesPermitidas(Config.usuario));
        }

        listaPermissao.clear();

    }

    public void fillAdicionadas() {

        DefaultTableModel tableModel = (DefaultTableModel) tPermissoes1.getModel();

        tableModel.setNumRows(0);

        Iterator<?> escolas = new ArrayList(listaPermissao.values()).iterator();

        while (escolas.hasNext()) {
            Permissao p = (Permissao) escolas.next();

            tableModel.addRow(new Object[]{p.getEscola(), p.getEscola().getNome(), p.isPermissao()});

        }

    }

    HashMap<Integer, Permissao> listaPermissao = new HashMap<>();

    public void addEscola(Escola e) {

        try {

            Permissao p = (Permissao) listaPermissao.get(e.getId());

            if (p == null) {
                p = new Permissao();
                p.setEscola(e);
                p.setPermissao(true);
                listaPermissao.put(e.getId(), p);

                fillAdicionadas();

            }
        } catch (NullPointerException ex) {

        }
    }

    public void apagarEscola(Escola e) {
        try {
            listaPermissao.remove(e.getId());
        } catch (NullPointerException ex) {
            JOptionPane.showMessageDialog(null, "Escolha uma escola primeiro.");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        tfLogin = new javax.swing.JTextField();
        tfNomeAdm = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tfEmail = new javax.swing.JTextField();
        cbAdm = new javax.swing.JCheckBox();
        jButton7 = new javax.swing.JButton();
        jLabel38 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jButton8 = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        tfSenha = new javax.swing.JPasswordField();
        tfSenha1 = new javax.swing.JPasswordField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        cbEscolaCidade = new javax.swing.JComboBox();
        cbCidadeUsuario = new javax.swing.JComboBox();
        jScrollPane4 = new javax.swing.JScrollPane();
        tPermissoes1 = new javax.swing.JTable();
        jButton21 = new javax.swing.JButton();

        jScrollPane1.setBorder(null);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Login:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Nome:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Email:");

        cbAdm.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cbAdm.setText("Gerente");
        cbAdm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAdmActionPerformed(evt);
            }
        });

        jButton7.setText("Salvar");
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel38.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel38.setText("Usuários");
        jLabel38.setToolTipText("");

        jButton8.setText("Cancelar");
        jButton8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jCheckBox1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCheckBox1.setText("Utilizar senha automática (ex.: 85421536)");
        jCheckBox1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCheckBox1StateChanged(evt);
            }
        });
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Senha:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("Confirmar senha:");

        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.white, java.awt.Color.lightGray, java.awt.Color.white));

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel34.setText("Cidade:");

        jButton3.setText("Remover escola");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setText("Escola:");

        cbEscolaCidade.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbEscolaCidadeItemStateChanged(evt);
            }
        });

        cbCidadeUsuario.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbCidadeUsuarioItemStateChanged(evt);
            }
        });

        tPermissoes1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "iD", "Escolas adicionadas"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tPermissoes1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tPermissoes1MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tPermissoes1);
        if (tPermissoes1.getColumnModel().getColumnCount() > 0) {
            tPermissoes1.getColumnModel().getColumn(0).setMinWidth(0);
            tPermissoes1.getColumnModel().getColumn(0).setPreferredWidth(0);
            tPermissoes1.getColumnModel().getColumn(0).setMaxWidth(0);
        }

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbEscolaCidade, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbCidadeUsuario, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel34)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbCidadeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbEscolaCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        jButton21.setText("Pesquisar");
        jButton21.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator4)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton21, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(cbAdm))
                    .addComponent(jCheckBox1)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel7)
                    .addComponent(jLabel38)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(235, 235, 235)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfNomeAdm, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tfEmail, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tfLogin, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tfSenha, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tfSenha1, javax.swing.GroupLayout.Alignment.LEADING)))
                .addGap(23, 23, 23))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton7, jButton8});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel38)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfNomeAdm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfSenha1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbAdm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7)
                    .addComponent(jButton8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton21, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1)
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbAdmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAdmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbAdmActionPerformed
    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        ProgressoEnviaEmailUsuario emailUsuario = null;
        if (!tfNomeAdm.getText().isEmpty() && !tfEmail.getText().isEmpty() && !tfLogin.getText().isEmpty() && tfSenha.getPassword().length != 0 && tfSenha1.getPassword().length != 0) {
            if (tfEmail.getText().matches("[a-z0-9]{4,}@[a-z]+(.com|.com.[a-z]+)")) {
                if (Arrays.equals(tfSenha.getPassword(), tfSenha1.getPassword())) {

                    synchronized (PainelUsuario.class) {

                        try {

                            jPanel1.removeAll();

                            jPanel1.setLayout(new BoxLayout(jPanel1, BoxLayout.LINE_AXIS));

                            JLabel jLabel = new JLabel("<html>Aguarde enviando email de confirmação<br>para o usuário cadastrado...");

                            jLabel.setFont(new java.awt.Font("Tahoma", 1, 18));

                            jPanel1.add(jLabel);

                            jPanel1.repaint();
                            jPanel1.revalidate();

                            String senha = "";

                            Usuario u = new Usuario();

                            u.setLogin(tfLogin.getText());
                            u.setNome(tfNomeAdm.getText());
                            u.setEmail(tfEmail.getText());
                            u.setCriadoPor(Config.usuario);

                            if (jCheckBox1.isSelected()) {
                                senha = RandomStringUtils.randomNumeric(8);
                                u.setSenhaAlterada(true);
                            } else {
                                senha = new String(tfSenha.getPassword());
                            }

                            u.setSenha(Config.criptografarSenha(senha));

                            if (cbAdm.isSelected()) {

                                u.setTipoUsuario(new TipoUsuarioDAO().getByName("Gerente"));

                            } else {
                                u.setTipoUsuario(new TipoUsuarioDAO().getByName("Funcionário"));
                            }

                            new UsuarioDAO().salvar(u);

                            Iterator<?> permissoes = new ArrayList(listaPermissao.values()).iterator();

                            while (permissoes.hasNext()) {

                                Permissao p = (Permissao) permissoes.next();

                                p.setUsuario(u);

                                new PermissaoDAO().salvar(p);

                            }

                            MensagemAguarde ma = new MensagemAguarde();

                            ma.setVisible(true);

                            emailUsuario = new ProgressoEnviaEmailUsuario(ma, u, senha);

                            emailUsuario.execute();

                        } catch (ConstraintViolationException ex) {
                            JOptionPane.showMessageDialog(null, "Login já existente.");
                        }

                        tfNomeAdm.setText(null);
                        tfEmail.setText(null);
                        tfLogin.setText(null);
                        tfSenha.setText(null);
                        tfSenha1.setText(null);

                        cbAdm.setSelected(false);
                        jCheckBox1.setSelected(false);
                        tfSenha.setEnabled(true);
                        tfSenha1.setEnabled(true);

                        removeAll();

                        initComponents();
                        init();

                        fillAdicionadas();

                        repaint();
                        revalidate();

                    }

                } else {
                    JOptionPane.showMessageDialog(null, "Senhas não coincidem.", "Resposta", JOptionPane.INFORMATION_MESSAGE);
                }

            } else {
                JOptionPane.showMessageDialog(null, "Email incorreto.", "Resposta", JOptionPane.INFORMATION_MESSAGE);

            }
        } else {
            JOptionPane.showMessageDialog(null, "Preencha os campos corretamente.", "Resposta", JOptionPane.INFORMATION_MESSAGE);

        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void cbCidadeUsuarioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbCidadeUsuarioItemStateChanged

        if (cbCidadeUsuario.getSelectedItem() instanceof Cidade) {

            if (Config.usuario.getTipoUsuario().getDescricao().equalsIgnoreCase("Administrador")) {
                Config.fillComboBox(cbEscolaCidade, new EscolaDAO().escolaDaCidade((Cidade) cbCidadeUsuario.getSelectedItem()));
            } else {
                Config.fillComboBox(cbEscolaCidade, new EscolaDAO().escolasPermitidasDaCidade(Config.usuario, (Cidade) cbCidadeUsuario.getSelectedItem()));
            }

            cbEscolaCidade.setEnabled(true);

        } else {
            cbEscolaCidade.setEnabled(false);
        }

    }//GEN-LAST:event_cbCidadeUsuarioItemStateChanged

    private void tPermissoes1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tPermissoes1MouseClicked

        if (tPermissoes1.getSelectedRowCount() > 0) {
            jButton3.setEnabled(true);
        } else {
            jButton3.setEnabled(false);
        }
    }//GEN-LAST:event_tPermissoes1MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        if (tPermissoes1.getSelectedRowCount() > 0) {

            apagarEscola((Escola) tPermissoes1.getValueAt(tPermissoes1.getSelectedRow(), 0));
            fillAdicionadas();
            Config.fillComboBox(cbEscolaCidade, new EscolaDAO().escolaDaCidade((Cidade) cbCidadeUsuario.getSelectedItem()));

            jButton3.setEnabled(false);

        } else {
            JOptionPane.showMessageDialog(null, "Selecione uma escola");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void cbEscolaCidadeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbEscolaCidadeItemStateChanged

        try {
            if (evt.getStateChange() == ItemEvent.SELECTED) {
                if (!cbCidadeUsuario.getSelectedItem().toString().equalsIgnoreCase("Selecione...")) {
                    addEscola((Escola) cbEscolaCidade.getSelectedItem());
                }
            }
        } catch (ClassCastException ex) {

        }
    }//GEN-LAST:event_cbEscolaCidadeItemStateChanged

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed

        removeAll();
        initComponents();

        repaint();
        revalidate();
        init();

    }//GEN-LAST:event_jButton8ActionPerformed

    private void jCheckBox1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jCheckBox1StateChanged


    }//GEN-LAST:event_jCheckBox1StateChanged

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        if (jCheckBox1.isSelected()) {
            tfSenha.setEnabled(false);
            tfSenha1.setEnabled(false);
            tfSenha.setText("---");
            tfSenha1.setText("---");
        } else {

            tfSenha.setEnabled(true);
            tfSenha1.setEnabled(true);
            tfSenha.setText(null);
            tfSenha1.setText(null);
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        new UsuariosCadastrados().setVisible(true);
    }//GEN-LAST:event_jButton21ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cbAdm;
    private javax.swing.JComboBox cbCidadeUsuario;
    private javax.swing.JComboBox cbEscolaCidade;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTable tPermissoes1;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfLogin;
    private javax.swing.JTextField tfNomeAdm;
    private javax.swing.JPasswordField tfSenha;
    private javax.swing.JPasswordField tfSenha1;
    // End of variables declaration//GEN-END:variables
}
