/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.senai.view;

import br.com.senai.dao.CidadeDAO;
import br.com.senai.dao.CursoDAO;
import br.com.senai.dao.Curso_e_EscolaDAO;
import br.com.senai.dao.EscolaDAO;
import br.com.senai.dao.MovimentacaoDAO;
import br.com.senai.dao.TipoDAO;
import br.com.senai.entities.Cidade;
import br.com.senai.entities.Curso_e_Escola;
import br.com.senai.entities.Escola;
import br.com.senai.entities.Tipo;
import br.com.senai.entities.Turma;
import br.com.senai.util.Config;
import java.awt.Image;
import java.awt.event.ItemEvent;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author Hugo
 */
public class PesquisaCursos extends javax.swing.JDialog {

    /**
     * Creates new form PesquisaCursos1
     */
    public PesquisaCursos() {
        initComponents();
        Config.configurarJanela(this);
        
        Config.fillComboBox(cbEscola, new EscolaDAO().escolasPermitidas(Config.usuario));
        Config.fillComboBox(cbCidade, new CidadeDAO().cidadesPermitidas(Config.usuario));
        Config.fillComboBox(cbTipoCursoAlteracao, new TipoDAO().listar());
        
        icon2.setIcon(new ImageIcon(new ImageIcon("imagens/icones/15.png").getImage().getScaledInstance(37, 37, Image.SCALE_SMOOTH)));
        
        iconRelatorio.setIcon(new ImageIcon(new ImageIcon("imagens/search.png").getImage().getScaledInstance(43, 43, Image.SCALE_SMOOTH)));
        
        AutoCompleteDecorator.decorate(cbCidade);
        
    }
    
    public static Turma turma = new Turma();
    public Curso_e_Escola cursoAlteracao;
    
    public static void fillTable(List<Curso_e_Escola> cursos) {
        
        DefaultTableModel tableModel = (DefaultTableModel) tCursos.getModel();
        
        tableModel.setNumRows(0);
        
        for (Curso_e_Escola curso : cursos) {
            tableModel.addRow(new Object[]{curso, curso.getPk().getCurso().getNome(), curso.getPk().getEscola().getNome(), curso.getPk().getEscola().getCidade().getNome(), curso.isAtivo()});
            
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AlterarCurso = new javax.swing.JDialog();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        cbTipoCursoAlteracao = new javax.swing.JComboBox();
        jButton8 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        icon2 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jCheckBox2 = new javax.swing.JCheckBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        cbCidade = new javax.swing.JComboBox();
        jLabel27 = new javax.swing.JLabel();
        cbEscola = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tCursos = new javax.swing.JTable();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        tfNomeCurso = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        iconRelatorio = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jCheckBox1 = new javax.swing.JCheckBox();

        AlterarCurso.setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);

        jLabel18.setText("Modalidade:");

        jLabel19.setText("Escola:");

        cbTipoCursoAlteracao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton8.setText("Cancelar");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton15.setText("Salvar");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        jLabel37.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel37.setText("Editar curso");
        jLabel37.setToolTipText("Alterar senha do usuário");

        jLabel1.setText("Nome do curso:");

        jLabel3.setText("jLabel3");

        jLabel7.setText("jLabel7");

        jCheckBox2.setText("Ativo");

        javax.swing.GroupLayout AlterarCursoLayout = new javax.swing.GroupLayout(AlterarCurso.getContentPane());
        AlterarCurso.getContentPane().setLayout(AlterarCursoLayout);
        AlterarCursoLayout.setHorizontalGroup(
            AlterarCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AlterarCursoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(AlterarCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox2)
                    .addComponent(jLabel7)
                    .addGroup(AlterarCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(AlterarCursoLayout.createSequentialGroup()
                            .addGap(4, 4, 4)
                            .addComponent(icon2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel37))
                        .addComponent(jSeparator3)
                        .addComponent(jLabel18)
                        .addComponent(cbTipoCursoAlteracao, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel19)
                        .addGroup(AlterarCursoLayout.createSequentialGroup()
                            .addComponent(jButton15)
                            .addGap(135, 135, 135)
                            .addComponent(jButton8))
                        .addComponent(jLabel1)
                        .addComponent(jLabel3)))
                .addGap(20, 20, 20))
        );
        AlterarCursoLayout.setVerticalGroup(
            AlterarCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AlterarCursoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(AlterarCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel37)
                    .addComponent(icon2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbTipoCursoAlteracao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AlterarCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jButton8)
                    .addComponent(jButton15))
                .addGap(20, 20, 20))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);
        setPreferredSize(new java.awt.Dimension(641, 483));

        jScrollPane2.setBorder(null);

        cbCidade.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione..." }));
        cbCidade.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbCidadeItemStateChanged(evt);
            }
        });

        jLabel27.setText("Cidade:");

        cbEscola.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione..." }));
        cbEscola.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbEscolaItemStateChanged(evt);
            }
        });

        jLabel4.setText("Escola:");

        tCursos.setAutoCreateRowSorter(true);
        tCursos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome do curso", "Escola", "Cidade", "Ativo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tCursos);
        if (tCursos.getColumnModel().getColumnCount() > 0) {
            tCursos.getColumnModel().getColumn(0).setMinWidth(0);
            tCursos.getColumnModel().getColumn(0).setPreferredWidth(0);
            tCursos.getColumnModel().getColumn(0).setMaxWidth(0);
        }

        jButton11.setText("Alterar");
        jButton11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setText("Remover");
        jButton12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton12.setRolloverEnabled(false);
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        tfNomeCurso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfNomeCursoKeyReleased(evt);
            }
        });

        jLabel2.setText("Nome do curso:");

        jButton1.setText("Pesquisar por todos os filtros");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("Pesquisar cursos");
        jLabel5.setToolTipText("");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Resultados encontrados:");
        jLabel6.setToolTipText("");

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jCheckBox1.setSelected(true);
        jCheckBox1.setText("Ativo");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1)
                    .addComponent(cbCidade, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbEscola, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfNomeCurso)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel27)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(iconRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jCheckBox1))
                        .addGap(303, 303, 303)))
                .addGap(20, 20, 20))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton11, jButton12, jButton2});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(iconRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfNomeCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbEscola, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton12)
                    .addComponent(jButton11)
                    .addComponent(jButton2))
                .addGap(20, 20, 20))
        );

        jScrollPane2.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cbCidadeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbCidadeItemStateChanged
        
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            if (!cbCidade.getSelectedItem().toString().equalsIgnoreCase("Selecione...")) {
                
                if (jCheckBox1.isSelected()) {
                    fillTable(new CursoDAO().pesquisa("ce.ativo=true and ce.pk.escola.cidade.id =" + ((Cidade) cbCidade.getSelectedItem()).getId() + "", Config.usuario));
                } else {
                    fillTable(new CursoDAO().pesquisa("ce.ativo=false and ce.pk.escola.cidade.id =" + ((Cidade) cbCidade.getSelectedItem()).getId() + "", Config.usuario));
                    
                }
                
            } else {
                DefaultTableModel dtmTabela = (DefaultTableModel) tCursos.getModel();
                dtmTabela.setNumRows(0);
            }
            
        }
    }//GEN-LAST:event_cbCidadeItemStateChanged

    private void cbEscolaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbEscolaItemStateChanged
        
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            
            if (!cbEscola.getSelectedItem().toString().equalsIgnoreCase("Selecione...")) {
                
                if (!jCheckBox1.isSelected()) {
                    fillTable(new CursoDAO().pesquisa("ce.ativo=false and ce.pk.escola.id =" + ((Escola) cbEscola.getSelectedItem()).getId() + "", Config.usuario));
                } else {
                    fillTable(new CursoDAO().pesquisa("ce.ativo=true and ce.pk.escola.id =" + ((Escola) cbEscola.getSelectedItem()).getId() + "", Config.usuario));
                }
                
            }
            
        } else {
            DefaultTableModel dtmTabela = (DefaultTableModel) tCursos.getModel();
            dtmTabela.setNumRows(0);
        }

    }//GEN-LAST:event_cbEscolaItemStateChanged

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        
        if (tCursos.getSelectedRowCount() > 0) {
            
            cursoAlteracao = (Curso_e_Escola) tCursos.getValueAt(tCursos.getSelectedRow(), 0);
            
            jLabel3.setText(cursoAlteracao.getPk().getCurso().getNome());
            cbTipoCursoAlteracao.setSelectedItem(cursoAlteracao.getTipo());
            jLabel7.setText(cursoAlteracao.getPk().getEscola().getNome());
            jCheckBox2.setSelected(cursoAlteracao.isAtivo());
            
            AlterarCurso.pack();
            AlterarCurso.setTitle("Alterar curso - ");
            Config.configurarJanela(AlterarCurso);
            AlterarCurso.setLocationRelativeTo(null);
            AlterarCurso.setVisible(true);
            
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um curso.");
        }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        
        if (tCursos.getSelectedRowCount() > 0) {
            
            Curso_e_Escola ce = (Curso_e_Escola) tCursos.getValueAt(tCursos.getSelectedRow(), 0);
            
            if (new MovimentacaoDAO().listarMovimentacoesDoCurso(ce).isEmpty()) {
                
                if (JOptionPane.showConfirmDialog(null, "Deseja excluir esse curso?\nNome:" + ce.getPk().getCurso().getNome() + "\nEscola: " + ce.getPk().getEscola().getNome() + "\n*Não será possível reverter o processo", "Confirmar exclusão", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                    
                    new Curso_e_EscolaDAO().deletar(ce);
                    
                    JOptionPane.showMessageDialog(null, "Curso deletado.");
                    
                    PainelGerenciarCurso.fillTCursos();
                    
                    DefaultTableModel dtmTabela = (DefaultTableModel) tCursos.getModel();
                    dtmTabela.setNumRows(0);
                    
                }
            } else {
                
                if (Config.mensagemDeConfirmacaoExclusao("Curso com movimentação.\n Deseja torná-lo inativo ?\nNome: " + ce.getPk().getCurso().getNome() + "\nEscola: " + ce.getPk().getEscola().getNome()) == JOptionPane.YES_OPTION) {
                    
                    ce.setAtivo(false);
                    
                    new Curso_e_EscolaDAO().atualizar(ce);
                    
                    JOptionPane.showMessageDialog(null, "Curso atualizado.");
                    
                    PainelGerenciarCurso.fillTCursos();
                    
                    DefaultTableModel dtmTabela = (DefaultTableModel) tCursos.getModel();
                    dtmTabela.setNumRows(0);
                    
                }
                
            }
            
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um curso.");
        }

    }//GEN-LAST:event_jButton12ActionPerformed

    private void tfNomeCursoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfNomeCursoKeyReleased
        
        if (jCheckBox1.isSelected()) {
            fillTable(new CursoDAO().pesquisa("ce.ativo=true and c.nome like '%" + tfNomeCurso.getText() + "%'", Config.usuario));
        } else {
            fillTable(new CursoDAO().pesquisa("ce.ativo=false and c.nome like '%" + tfNomeCurso.getText() + "%'", Config.usuario));
        }

    }//GEN-LAST:event_tfNomeCursoKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        if (!tfNomeCurso.getText().isEmpty() && !cbEscola.getSelectedItem().toString().equalsIgnoreCase("Selecione...") && !cbCidade.getSelectedItem().toString().equalsIgnoreCase("Selecione...")) {
            
            if (jCheckBox1.isSelected()) {
                fillTable(new CursoDAO().pesquisa("ce.ativo=true and c.nome like '%" + tfNomeCurso.getText() + "%' and ce.pk.escola.id =" + ((Escola) cbEscola.getSelectedItem()).getId() + " and ce.pk.escola.cidade.id =" + ((Cidade) cbCidade.getSelectedItem()).getId() + "", Config.usuario));
            } else {
                fillTable(new CursoDAO().pesquisa("ce.ativo=false and c.nome like '%" + tfNomeCurso.getText() + "%' and ce.pk.escola.id =" + ((Escola) cbEscola.getSelectedItem()).getId() + " and ce.pk.escola.cidade.id =" + ((Cidade) cbCidade.getSelectedItem()).getId() + "", Config.usuario));
            }
            
        } else {
            JOptionPane.showMessageDialog(null, "Selecione as informações.");
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        AlterarCurso.dispose();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        
        cursoAlteracao.setTipo((Tipo) cbTipoCursoAlteracao.getSelectedItem());
        cursoAlteracao.setAtivo(jCheckBox2.isSelected());
        
        new Curso_e_EscolaDAO().atualizar(cursoAlteracao);
        
        AlterarCurso.dispose();
        
        JOptionPane.showMessageDialog(null, "Curso atualizado.");
        
        PainelGerenciarCurso.fillTCursos();
        
        DefaultTableModel dtmTabela = (DefaultTableModel) tCursos.getModel();
        dtmTabela.setNumRows(0);
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        
        if (jCheckBox1.isSelected()) {
            
            fillTable(new CursoDAO().pesquisa("ce.ativo=true", Config.usuario));
            
        } else {
            
            fillTable(new CursoDAO().pesquisa("ce.ativo=false", Config.usuario));
            
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog AlterarCurso;
    private javax.swing.JComboBox cbCidade;
    private javax.swing.JComboBox cbEscola;
    private static javax.swing.JComboBox cbTipoCursoAlteracao;
    private javax.swing.JLabel icon2;
    private javax.swing.JLabel iconRelatorio;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton8;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private static javax.swing.JTable tCursos;
    private javax.swing.JTextField tfNomeCurso;
    // End of variables declaration//GEN-END:variables
}
