/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.senai.view;

import br.com.senai.dao.AlunoDAO;
import br.com.senai.dao.Curso_e_EscolaDAO;
import br.com.senai.dao.EscolaDAO;
import br.com.senai.dao.TurmaDAO;
import br.com.senai.dao.TurnoDAO;
import br.com.senai.entities.Aluno;
import br.com.senai.entities.Curso;
import br.com.senai.entities.Curso_e_Escola;
import br.com.senai.entities.Escola;
import br.com.senai.entities.Turma;
import br.com.senai.entities.Turno;
import br.com.senai.util.Config;
import java.awt.Image;
import java.awt.event.ItemEvent;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hugo
 */
public class PesquisaAlunos extends javax.swing.JDialog {

    /**
     * Creates new form PesquisaAlunos1
     */
    public PesquisaAlunos() {
        initComponents();
        
        Config.configurarJanela(this);
        Config.fillComboBox(cbEscola, new EscolaDAO().escolasPermitidas(Config.usuario));
        Config.fillComboBox(cbTurno, new TurnoDAO().listar());
        iconRelatorio.setIcon(new ImageIcon(new ImageIcon("imagens/search.png").getImage().getScaledInstance(43, 43, Image.SCALE_SMOOTH)));
        cbCurso.setEnabled(false);
        
    }
    
    Curso_e_Escola curso_e_Escola = null;
    boolean turnoAtivado;
    Aluno a;
    
    public void fillTable(String query) {
        
        DefaultTableModel tableModel = (DefaultTableModel) tAlunosCadastrados.getModel();
        
        tableModel.setNumRows(0);
        
        for (Aluno aluno : new AlunoDAO().pesquisar(query, Config.usuario)) {
            
            tableModel.addRow(new Object[]{aluno, aluno.getAluno(), aluno.getTurma().getNome(), aluno.isAtivo()});
            
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AlterarAluno = new javax.swing.JDialog();
        jLabel9 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        cbAlunoAtivo = new javax.swing.JCheckBox();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        icon1 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        tfNomeEditarAluno = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        tfRaALuno = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tAlunosCadastrados = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        cbEscola = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        cbCurso = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        cbTurno = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        cbTurma = new javax.swing.JComboBox();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        iconRelatorio = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jButton30 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();

        AlterarAluno.setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);

        jLabel9.setText("RA:");

        jLabel20.setText("Turma:");

        cbAlunoAtivo.setText("Ativo");

        jButton19.setText("Salvar");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });

        jButton20.setText("Cancelar");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });

        jLabel1.setText("jLabel1");

        jLabel36.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel36.setText("Editar aluno");
        jLabel36.setToolTipText("Alterar senha do usuário");

        jLabel2.setText("jLabel2");

        jLabel12.setText("Nome:");

        javax.swing.GroupLayout AlterarAlunoLayout = new javax.swing.GroupLayout(AlterarAluno.getContentPane());
        AlterarAluno.getContentPane().setLayout(AlterarAlunoLayout);
        AlterarAlunoLayout.setHorizontalGroup(
            AlterarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AlterarAlunoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(AlterarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel2)
                    .addGroup(AlterarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(cbAlunoAtivo)
                        .addGroup(AlterarAlunoLayout.createSequentialGroup()
                            .addComponent(jButton19, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(38, 38, 38)
                            .addComponent(jButton20, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(AlterarAlunoLayout.createSequentialGroup()
                            .addGap(4, 4, 4)
                            .addComponent(icon1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel36))
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel20)
                        .addComponent(jLabel9)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(tfNomeEditarAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );
        AlterarAlunoLayout.setVerticalGroup(
            AlterarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AlterarAlunoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(AlterarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel36)
                    .addComponent(icon1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfNomeEditarAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel20)
                .addGap(12, 12, 12)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbAlunoAtivo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AlterarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton19)
                    .addComponent(jButton20))
                .addGap(20, 20, 20))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pesquisar alunos -");
        setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);

        jScrollPane1.setBorder(null);

        tfRaALuno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfRaALunoKeyReleased(evt);
            }
        });

        jLabel5.setText("RA:");

        tAlunosCadastrados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "RA", "Turma", "Ativo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(tAlunosCadastrados);
        if (tAlunosCadastrados.getColumnModel().getColumnCount() > 0) {
            tAlunosCadastrados.getColumnModel().getColumn(0).setMinWidth(0);
            tAlunosCadastrados.getColumnModel().getColumn(0).setPreferredWidth(0);
            tAlunosCadastrados.getColumnModel().getColumn(0).setMaxWidth(0);
        }

        jLabel4.setText("Escola:");

        cbEscola.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbEscola.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbEscolaItemStateChanged(evt);
            }
        });

        jLabel6.setText("Curso:");

        cbCurso.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbCursoItemStateChanged(evt);
            }
        });

        jLabel7.setText("Turno:");

        cbTurno.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbTurnoItemStateChanged(evt);
            }
        });

        jLabel8.setText("Turma:");

        cbTurma.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbTurmaItemStateChanged(evt);
            }
        });

        jButton28.setText("Alterar");
        jButton28.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton28ActionPerformed(evt);
            }
        });

        jButton29.setText("Remover");
        jButton29.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton29ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setText("Pesquisar alunos");
        jLabel10.setToolTipText("");

        jButton30.setText("Cancelar");
        jButton30.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton30ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Resultados encontrados:");
        jLabel11.setToolTipText("");

        jCheckBox1.setSelected(true);
        jCheckBox1.setText("Ativo");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2)
                    .addComponent(jScrollPane5)
                    .addComponent(tfRaALuno)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton28, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton29, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton30, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cbEscola, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(iconRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel8))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(cbTurma, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(cbCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(cbTurno, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox1)
                            .addComponent(jLabel11))
                        .addGap(429, 429, 429)))
                .addGap(20, 20, 20))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cbCurso, cbTurno});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton28, jButton29, jButton30});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(iconRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfRaALuno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbEscola, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbTurno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbTurma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton28)
                    .addComponent(jButton29)
                    .addComponent(jButton30))
                .addGap(20, 20, 20))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tfRaALunoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfRaALunoKeyReleased
        if (jCheckBox1.isSelected()) {
            fillTable("a.pk.id like '%" + tfRaALuno.getText() + "%' and a.ativo=true");
        } else {
            fillTable("a.pk.id like '%" + tfRaALuno.getText() + "%' and a.ativo=false");
        }
    }//GEN-LAST:event_tfRaALunoKeyReleased

    private void cbEscolaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbEscolaItemStateChanged
        
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            if (!cbEscola.getSelectedItem().toString().equalsIgnoreCase("Selecione...")) {
                
                Config.fillComboBox(cbCurso, new Curso_e_EscolaDAO().cursosDaEscola((Escola) cbEscola.getSelectedItem()));
                cbCurso.setEnabled(true);
            } else {
                
                cbCurso.removeAllItems();
                cbCurso.addItem(new Object() {
                    
                    @Override
                    public String toString() {
                        return "Selecione...";
                    }
                });
                cbCurso.setEnabled(false);
            }
        }
    }//GEN-LAST:event_cbEscolaItemStateChanged

    private void cbCursoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbCursoItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            
            if (!cbCurso.getSelectedItem().toString().equalsIgnoreCase("Selecione...")) {
                
                Config.fillComboBox(cbTurno, new TurnoDAO().listar());
                curso_e_Escola = new Curso_e_EscolaDAO().getCurso_e_Escola((Curso) cbCurso.getSelectedItem(), (Escola) cbEscola.getSelectedItem());
                Config.fillComboBox(cbTurma, new TurmaDAO().pesquisarPorCurso(curso_e_Escola));
            } else {
                Config.limparComboBox(cbTurma);
                
            }
        }
    }//GEN-LAST:event_cbCursoItemStateChanged

    private void cbTurnoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbTurnoItemStateChanged
        
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            
            if (cbTurno.getSelectedItem().toString().equalsIgnoreCase("Selecione...")) {
                turnoAtivado = false;
                Config.limparComboBox(cbTurma);
                
            } else {
                turnoAtivado = true;
                
                if (!cbCurso.getSelectedItem().toString().equalsIgnoreCase("Selecione...")) {
                    
                    Config.fillComboBox(cbTurma, new TurmaDAO().pesquisarPorCursoETurno(curso_e_Escola, (Turno) cbTurno.getSelectedItem()));
                    
                }
                
            }
        }
    }//GEN-LAST:event_cbTurnoItemStateChanged

    private void cbTurmaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbTurmaItemStateChanged
        
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            
            if (!cbTurma.getSelectedItem().toString().equalsIgnoreCase("Selecione...")) {
                
                if (jCheckBox1.isSelected()) {
                    fillTable("a.pk.turma.nome='" + cbTurma.getSelectedItem().toString() + "' and a.ativo=true");
                } else {
                    fillTable("a.pk.turma.nome='" + cbTurma.getSelectedItem().toString() + "' and a.ativo=false");
                }
                
                cbTurma.setSelectedIndex(0);
                
            }
        }
    }//GEN-LAST:event_cbTurmaItemStateChanged

    private void jButton28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton28ActionPerformed
        
        if (tAlunosCadastrados.getSelectedRowCount() > 0) {
            
            a = (Aluno) tAlunosCadastrados.getValueAt(tAlunosCadastrados.getSelectedRow(), 0);
            tfNomeEditarAluno.setText(a.getNome());
            jLabel1.setText(Long.toString(a.getAluno()));
            jLabel2.setText(a.getTurma().getNome());
            cbAlunoAtivo.setSelected(a.isAtivo());
            AlterarAluno.pack();
            icon1.setIcon(new ImageIcon(new ImageIcon("imagens/icones/15.png").getImage().getScaledInstance(37, 37, Image.SCALE_SMOOTH)));
            
            AlterarAluno.setLocationRelativeTo(null);
            
            Config.configurarJanela(AlterarAluno);
            
            AlterarAluno.setVisible(true);
            
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um aluno.");
        }
    }//GEN-LAST:event_jButton28ActionPerformed

    private void jButton29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton29ActionPerformed
        if (tAlunosCadastrados.getSelectedRowCount() > 0) {
            
            try {
                
                Aluno a = (Aluno) tAlunosCadastrados.getValueAt(tAlunosCadastrados.getSelectedRow(), 0);
                String movimentacao = "";
                
                if (!new AlunoDAO().getMovimentacoes(a).isEmpty()) {
                    movimentacao = "Há movimentações para esse aluno.";
                }
                
                if (JOptionPane.showConfirmDialog(null, "Deseja excluir esse aluno?\nRA:" + a.getAluno() + "\nTurma:" + a.getTurma() + "\n*Não será possível reverter o processo\n" + movimentacao, "Confirmar exclusão", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                    
                    if (new AlunoDAO().getMovimentacoes(a).isEmpty()) {
                        new AlunoDAO().deletar(a);
                        fillTable("a.pk.id like '%" + tfRaALuno.getText() + "%'");
                    } else {
                        a.setAtivo(false);
                        new AlunoDAO().atualizar(a);
                    }
                    
                    PainelAluno.atualizarAlunos();
                    
                    toFront();
                    
                }
            } catch (NullPointerException ex) {
                
            }
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um aluno.");
        }
    }//GEN-LAST:event_jButton29ActionPerformed

    private void jButton30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton30ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton30ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        //
        //        if (jCheckBox1.isSelected()) {
        //            fillTable("a.pk.turma.nome='" + cbTurma.getSelectedItem().toString() + "' and ");
        //
        //        } else {
        //            fillTable("a.pk.turma.nome='" + cbTurma.getSelectedItem().toString() + "'");
        //        }

    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        
        if (!tfNomeEditarAluno.getText().isEmpty()) {
            Aluno a = new Aluno();
            
            Turma t = new TurmaDAO().getNome(jLabel2.getText());
            a.setNome(tfNomeEditarAluno.getText());
            a.setAluno(Long.parseLong(jLabel1.getText()));
            a.setAtivo(cbAlunoAtivo.isSelected());
            a.setTurma(t);
            
            if (a.isAtivo()) {
                
                Aluno a1 = new AlunoDAO().validarTurma(a.getAluno(), t.getTurno());
                
                if (a1 != null) {
                    
                    if (JOptionPane.showConfirmDialog(null, "Foi encontrado uma turma:" + a1.getTurma().getNome() + " \n ativa no turno:" + a1.getTurma().getTurno().getTurno() + "\n com o usuário:" + a1.getAluno(), "Confirmar alteração de turma", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                        
                        a1.setAtivo(false);
                        new AlunoDAO().atualizar(a1);
                        
                        new AlunoDAO().atualizar(a);
                        
                        JOptionPane.showMessageDialog(null, "salvo com sucesso!");
                    }
                    
                } else {
                    new AlunoDAO().atualizar(a);
                    
                    JOptionPane.showMessageDialog(null, "salvo com sucesso!");
                }
                
            } else {
                new AlunoDAO().atualizar(a);
                
                JOptionPane.showMessageDialog(null, "salvo com sucesso!");
            }
            
            fillTable("a.pk.id like '%" + tfRaALuno.getText() + "%'");
            
            PainelAluno.atualizarAlunos();
            
            AlterarAluno.dispose();
            
            toFront();
        } else {
            Config.mensagemDeAviso("Preencha os campos corretamente");
        }
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        AlterarAluno.dispose();
    }//GEN-LAST:event_jButton20ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog AlterarAluno;
    private javax.swing.JCheckBox cbAlunoAtivo;
    private javax.swing.JComboBox cbCurso;
    private javax.swing.JComboBox cbEscola;
    private static javax.swing.JComboBox cbTurma;
    private javax.swing.JComboBox cbTurno;
    private javax.swing.JLabel icon1;
    private javax.swing.JLabel iconRelatorio;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton30;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable tAlunosCadastrados;
    private javax.swing.JTextField tfNomeEditarAluno;
    private javax.swing.JTextField tfRaALuno;
    // End of variables declaration//GEN-END:variables
}
