/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.senai.view.nova;

import br.com.senai.view.*;
import br.com.senai.dao.AlunoDAO;
import br.com.senai.dao.Curso_e_EscolaDAO;
import br.com.senai.dao.EscolaDAO;
import br.com.senai.dao.TurmaDAO;
import br.com.senai.entities.Aluno;
import br.com.senai.entities.Curso;
import br.com.senai.entities.Curso_e_Escola;
import br.com.senai.entities.Escola;
import br.com.senai.entities.Turma;
import br.com.senai.util.Config;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import org.hibernate.HibernateException;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author Hugo
 */
public class AlunosFuncionariosNovoEdita extends javax.swing.JPanel {

    /**
     * Creates new form PainelAluno
     */
    public AlunosFuncionariosNovoEdita() {
        initComponents();

        Config.fillComboBox(cbTurma, new TurmaDAO().turmasPermitidas(Config.usuario));
        Config.fillComboBox(cbEscola, new EscolaDAO().escolasPermitidas(Config.usuario));

        AutoCompleteDecorator.decorate(cbTurma);
        AutoCompleteDecorator.decorate(cbCurso);

        cbCurso.setEnabled(false);

    }

    public void cadastrar() {

        if (!tfRaALuno.getText().isEmpty() && !tfNome.getText().isEmpty() && !cbTurma.getSelectedItem().toString().equalsIgnoreCase("Selecione...")) {

            try {

//                System.out.println(tfRaALuno.getText());
                Turma t = (Turma) cbTurma.getSelectedItem();
                Long id = Long.parseLong(tfRaALuno.getText());

                if (new TurmaDAO().isAtiva(t) != null) {

                    if (new AlunoDAO().validarTurma(id, t.getTurno()) == null) {

                        Aluno a = new Aluno();

                        a.setAluno(id);
                        a.setNome(tfNome.getText());
                        a.setTurma(t);
                        a.setAtivo(true);

                        try {
                            new AlunoDAO().salvar(a);

                            new MensagemSalvo().setVisible(true);

                        } catch (HibernateException e) {
                            new MensagemNaoSalvo().setVisible(true);

                        }

                    } else {
                        JOptionPane.showMessageDialog(null, "O aluno já está realizando um curso nesse turno.");
                        tfRaALuno.setText(null);
                        tfRaALuno.requestFocus();
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "A turma não está ativa no momento.");
                }

            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(null, "Dado inválido \n *somente números", "Erro", JOptionPane.ERROR_MESSAGE);
                tfRaALuno.setText(null);
                tfRaALuno.requestFocus();
            }

        } else {

            JOptionPane.showMessageDialog(null, "Preencha os campos corretamente.", "Resposta", JOptionPane.INFORMATION_MESSAGE);
            tfRaALuno.setText(null);
            tfRaALuno.requestFocus();

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        tfRaALuno = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cbTurma = new javax.swing.JComboBox();
        tAlunos = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        cbEscola = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        cbCurso = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        tfNome = new javax.swing.JTextField();

        jScrollPane1.setBorder(null);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("RA (Registro do Aluno):");

        tfRaALuno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfRaALunoKeyPressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Turma:");

        cbTurma.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        tAlunos.setText("Salvar");
        tAlunos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tAlunos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tAlunosActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Escola:");

        cbEscola.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbEscola.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbEscolaItemStateChanged(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Curso:");

        cbCurso.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbCurso.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbCursoItemStateChanged(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Nome:");

        tfNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(tfRaALuno, javax.swing.GroupLayout.DEFAULT_SIZE, 507, Short.MAX_VALUE)
                    .addComponent(cbTurma, 0, 507, Short.MAX_VALUE)
                    .addComponent(tAlunos, javax.swing.GroupLayout.DEFAULT_SIZE, 507, Short.MAX_VALUE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(cbEscola, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbCurso, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9)
                    .addComponent(tfNome))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfRaALuno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbEscola, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbTurma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tAlunos)
                .addContainerGap())
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tfRaALunoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfRaALunoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            cadastrar();
        }
    }//GEN-LAST:event_tfRaALunoKeyPressed

    private void tAlunosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tAlunosActionPerformed

        cadastrar();
    }//GEN-LAST:event_tAlunosActionPerformed

    private void cbEscolaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbEscolaItemStateChanged

        if (cbEscola.getSelectedItem() instanceof Escola) {
            Config.fillComboBox(cbCurso, new Curso_e_EscolaDAO().cursosDaEscola((Escola) cbEscola.getSelectedItem()));
            cbCurso.setEnabled(true);
        } else {
            Config.limparComboBox(cbCurso);
            cbCurso.setEnabled(false);

        }
    }//GEN-LAST:event_cbEscolaItemStateChanged

    private void cbCursoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbCursoItemStateChanged

        if (cbCurso.getSelectedItem() instanceof Curso) {

            Curso_e_Escola curso_e_Escola = new Curso_e_EscolaDAO().getCurso_e_Escola((Curso) cbCurso.getSelectedItem(), (Escola) cbEscola.getSelectedItem());
            Config.fillComboBox(cbTurma, new TurmaDAO().pesquisarPorCurso(curso_e_Escola));
        } else {
            Config.limparComboBox(cbTurma);

        }

    }//GEN-LAST:event_cbCursoItemStateChanged

    private void tfNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNomeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbCurso;
    private javax.swing.JComboBox cbEscola;
    private javax.swing.JComboBox cbTurma;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton tAlunos;
    private javax.swing.JTextField tfNome;
    private static javax.swing.JTextField tfRaALuno;
    // End of variables declaration//GEN-END:variables
}
